// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c384e2bd-c8dc-4dff-bacd-4c25163a7f0b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;    // Secret device password

void onNH3Change();
void onPM25Change();
void onTEMPERATUREChange();
void onCO2Change();
void onHUMIDITYChange();

float nH3;
float pM25;
CloudTemperatureSensor tEMPERATURE;
int cO2;
CloudRelativeHumidity hUMIDITY;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(nH3, READWRITE, ON_CHANGE, onNH3Change);
  ArduinoCloud.addProperty(pM25, READWRITE, ON_CHANGE, onPM25Change);
  ArduinoCloud.addProperty(tEMPERATURE, READWRITE, ON_CHANGE, onTEMPERATUREChange);
  ArduinoCloud.addProperty(cO2, READWRITE, ON_CHANGE, onCO2Change);
  ArduinoCloud.addProperty(hUMIDITY, READWRITE, ON_CHANGE, onHUMIDITYChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
